name: Test
on:
  pull_request:
  push: { branches: master }

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Login to DockerHub
    #   run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Build docker images
      run: docker compose build

    - name: Composer install
      run: docker compose run --rm php composer install

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: docker compose run --rm php ./vendor/bin/phpunit --coverage-clover ./coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
         token: ${{ secrets.CODE_COV_TOKEN }}
         files: ./coverage.xml
         verbose: true